import Head from 'next/head'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Magic Cursor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/magic.png" />
      </Head>
      <main>
            <Layout>
              
            </Layout>
      </main>
    </>
  )
}
